export const BASE_URL = 'https://localhost:5000/'
export const ITEMS_PER_PAGE = 20
export const DOCUMENT_TITLE = 'VBase'
export const DOCUMENT_TITLE_SEPARATOR = '-'

export const LOGOUT = {
    REQUESTED: 'LOGOUT_REQUESTED',
    PERFORMED: 'LOGOUT_PERFORMED'
}

export const LOGIN = {
	REQUESTED: 'LOGIN_REQUESTED',
	CHECKED: 'LOGIN_CHECKED'
}

export const SEARCH = {
	TOGGLEADVANCED: 'SEARCH_TOGGLEADVANCED',
	CHANGEDSIMPLE: 'SEARCH_CHANGEDSIMPLE',
	SUBMITTEDSIMPLE: 'SEARCH_SUBMITTEDSIMPLE',
	CHANGEDADVANCED: 'SEARCH_CHANGEDADVANCED',
	SUBMITTEDADVANCED: 'SEARCH_SUBMITTEDADVANCED',
	RESETFIELDREQUESTED: 'SEARCH_RESETFIELDREQUESTED'
}

export const RESULTS = {
	REQUESTED: 'RESULTS_REQUESTED',
	RETRIEVED: 'RESULTS_RETRIEVED',
	FAILED: 'RESULTS_FAILED',
	PAGEREQUESTED: 'RESULTS_PAGEREQUESTED',
	BACKREQUESTED: 'RESULTS_BACKREQUESTED'
}

export const CONTACT = {
	VALUECHANGED: 'CONTACT_VALUECHANGED',
	SUBMITTED: 'CONTACT_SUBMITTED',
	FAILED: 'CONTACT_FAILED',
	SENTSUCCESFULLY: 'CONTACT_SENTSUCCESFULLY'
}

export const GAME = {
	REQUESTEDINFO: 'GAME_REQUESTEDINFO',
	FAILEDONURL: 'GAME_FAILEDONURL',
	FAILEDLOADING: 'GAME_FAILEDLOADING',
	INFORETRIEVED: 'GAME_INFORETRIEVED',
	RELATEDGAMESRETRIEVED: 'GAME_RELATEDGAMESRETRIEVED'
}

export const INFO = {
	CONTENTREQUESTED: 'INFO_CONTENTREQUESTED',
	FAILEDLOADING: 'INFO_FAILEDLOADING',
	CONTENTRETRIEVED: 'INFO_CONTENTRETRIEVED',
}